version: '3.10'

services:
  postgres_db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: postgres_db
  web:
    build: .
    volumes:
      - .:/app
      - ./staticfiles:/core/staticfiles/
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    container_name: web
    env_file:
      - .env
  nginx:
    image: linuxserver/swag
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Bishkek
      - URL=alimmah.dev
      - SUBDOMAINS=api
      - VALIDATION=http
      - ONLY_SUBDOMAINS=true
      - STAGING=false
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - lets:/config
      - ./nginx/ssl.conf:/config/nginx/site-confs/ssl/ssl.conf
      - ./nginx/nginx.conf:/config/nginx/site-confs/default.conf
      - ./staticfiles:/core/staticfiles/

volumes:
  postgres_data:
  lets:
